# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-12-04 15:28
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Deputy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('lifetime', models.SmallIntegerField()),
                ('appearance', models.SmallIntegerField()),
                ('absent_number', models.SmallIntegerField()),
                ('accept', models.FloatField()),
                ('denied', models.FloatField()),
                ('refrain', models.FloatField()),
                ('absent_percentage', models.FloatField()),
                ('appearance_percentage', models.FloatField()),
                ('protest_level', models.FloatField()),
                ('faction_protest_level', models.FloatField()),
            ],
            options={
                'verbose_name_plural': 'deputies',
            },
        ),
        migrations.CreateModel(
            name='DeputyVote',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vote', models.CharField(max_length=7)),
                ('deputy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='duma.Deputy')),
            ],
        ),
        migrations.CreateModel(
            name='Faction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('about', models.TextField()),
                ('logo', models.CharField(max_length=100)),
                ('color1', models.CharField(max_length=7)),
                ('color2', models.CharField(max_length=7)),
                ('av_accept', models.FloatField()),
                ('av_denied', models.FloatField()),
                ('av_refrain', models.FloatField()),
                ('av_appearance', models.FloatField()),
                ('av_absent', models.FloatField()),
                ('protest_level', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='FactionVotes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('f_appearance_v', models.SmallIntegerField()),
                ('av_accept_v', models.FloatField()),
                ('av_denied_v', models.FloatField()),
                ('av_refrain_v', models.FloatField()),
                ('absent_v', models.FloatField()),
                ('faction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='duma.Faction')),
            ],
        ),
        migrations.CreateModel(
            name='LawVoting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField()),
                ('vote_date', models.DateField()),
                ('appearance_v', models.SmallIntegerField()),
                ('overall_accept_v', models.FloatField()),
                ('overall_denied_v', models.FloatField()),
                ('overall_refrain_v', models.FloatField()),
                ('overall_absent_v', models.FloatField()),
                ('overall_appearance_v', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='OverallStats',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('appearance', models.IntegerField()),
                ('overall_accept', models.FloatField()),
                ('overall_denied', models.FloatField()),
                ('overall_refrain', models.FloatField()),
                ('overall_absent', models.FloatField()),
                ('overall_appearance', models.FloatField()),
            ],
        ),
        migrations.AddField(
            model_name='factionvotes',
            name='law_voting',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='duma.LawVoting'),
        ),
        migrations.AddField(
            model_name='faction',
            name='votes',
            field=models.ManyToManyField(through='duma.FactionVotes', to='duma.LawVoting'),
        ),
        migrations.AddField(
            model_name='deputyvote',
            name='law_voting',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='duma.LawVoting'),
        ),
        migrations.AddField(
            model_name='deputy',
            name='faction',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='duma.Faction'),
        ),
        migrations.AddField(
            model_name='deputy',
            name='votes',
            field=models.ManyToManyField(through='duma.DeputyVote', to='duma.LawVoting'),
        ),
    ]
